name: Update Profile Readme
on:
  schedule:
    - cron: '0 * * * *' # every hour
jobs:
  generate-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install three @svg-canvas
      - name: Generate 3D Scene SVG
        run: node scripts/generate-3d-svg.js
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/3d-scene.svg
          git commit -m "chore: update 3D scene" || echo "No changes"
          git push
